### ISSUE TITLE
Escape $ ?

### ISSUE THREAD

**Issue by boatmisser** [orctom/gradle-archetype-plugin#16]
More of a question than an issue, but is there anyway to escape $.
In my files with ${variable} the $ is being replaced by __DOLLAR__

**Comment by orctom** [comment]
Nope, I came across the same issue when I have jquery in my template. Not found a way yet, so I have to add it to `.nontemplate`.

**Comment by boatmisser** [comment]
I'm not a groovy expert so I might be wrong, but...

In FileUtils.groovy shouldn't resolved be reassigned during the replaceAll:
Also, should the second parameter be escaped (I thought the first param was regex but the second was the raw replacement string).
E.g.
```
String resolved = engine.createTemplate(ready).make(binding)
resolved = resolved.replaceAll('__DOLLAR__', '$')
resolved.replaceAll('__AT__', '@')
```

**Comment by orctom** [comment]
Good catch! You are absolutely correct! I missed it when merging from PR#14.

I thought it's the old problem that I encountered where I have to add the ".nontemplate", apparently it's not. And the bad thing is that i can't remember how to reproduce the issue that I had months ago.

Well, thank you @boatmisser !

**Comment by orctom** [comment]
@boatmisser Please checkout `1.4.4`.

**Comment by boatmisser** [comment]
$ is now working in 1.4.4.

Thanks for the quick turn around.
