### ISSUE TITLE
Gradle Archetype fails to replace keywords in a java file when input parameters annotated with more than one annotations 

### ISSUE THREAD

**Issue by harry9111985** [orctom/gradle-archetype-plugin#17]
@PostMapping
    public ResponseEntity<ProductDetail> createProduct(** @RequestBody @Valid ProductDetail product**) {
        log.info("REST[createProduct] Rx[{}]", toStringHelper.asString(product));

        ProductDetail productDetail = productDetailService.create(product);

        log.info("REST[createProduct] Tx[{}]", toStringHelper.asString(productDetail));
        return new ResponseEntity<>(productDetail, HttpStatus.OK);
    }

In the above code snippet , @RequestBody and @Valid are two annotations given to ProductDetail parameter . If we run the cleanArch generate archetype task , we get the following error :  

Failed to resolve variables in: 'C:\harish\projects\archetype\src\main\resources\templates\src\main\java\__packagePath__\model\web\rest\ProductDetailRestRestController.java]
No such property: RequestBody for class: groovy.lang.Binding

@orctom : Can you suggest any solution / configuration for the same if we are missing something? . If its an outstanding issue , is there an ETA for the fix ?

**Comment by orctom** [comment]
How's `1.4.5` doing?

**Comment by orctom** [comment]
I probably should trying to fix it. As you can escape `@` by `@@`, #14 
`1.4.5` might run into some other issue.
So, go either way, `@@` or update version to `1.4.5`.

**Comment by idooo** [comment]
@orctom just want to say - you are rockstar. Thanks for the fix!
