### ISSUE TITLE
Version 1.4.6 not found by gradle

### ISSUE THREAD

**Issue by dennistruemper** [orctom/gradle-archetype-plugin#20]
I used this with a local build and found out, that 1.4.6 is not downloaded via gradle. 1.4.5 is working, so I assume it is not published so short after release.

This is the Error:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'temp'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find gradle.plugin.com.orctom.gradle:gradle-archetype-plugin:1.4.6.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/com/orctom/gradle/gradle-archetype-plugin/1.4.6/gradle-archetype-plugin-1.4.6.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/orctom/gradle/gradle-archetype-plugin/1.4.6/gradle-archetype-plugin-1.4.6.jar
     Required by:
         :temp:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

**Comment by orctom** [comment]
It was caused by a bug in publish plugin, `1.4.6.3` should be working.

**Comment by dennistruemper** [comment]
@orctom It is working with the new Version, thanks a lot :-)
