### ISSUE TITLE
Need a way to add customized bindings prior to generation

### ISSUE THREAD

**Issue by lstreepy** [orctom/gradle-archetype-plugin#26]
Currently, the replacements (bindings) for the generation must be specified via properties or entered by the user.  If they come from the user, there's no way to create additional bindings based on the value of an existing binding.

As a simple example, I can currently do things like `@name.capitalize()@`, but if I need to perform more complicated transformation (or I need to use them in file names), it becomes cumbersome.

If the `generate` task supported a mechanism to allow the consuming project to modify the bindings just prior to generation (after all the current variable resolution has been performed), that would greatly simplify common transformations.  Using the example above, I could add a `capitalizedName` binding and then reference that within all the places needed.

I have worked up a simple implementation that allows the task to be configured with a `bindingProcessor` that is just a closure accepting the binding map as an argument.  The closure can then update the binding map as desired.  The closure is invoked just prior to starting the generation (i.e., the call to `FileUtils.generate`.  I can provide a Pull Request for this modification if you feel it would make a good addition to the project.

**Comment by orctom** [comment]
Does this work for you?
```
Command line :
-Dparam1=value1 -Dparam2=value2 -Dparam3=value3 ...


Programmably :
System.setProperty('com.orctom.gradle.archetype.binding.param1', value1)
```

**Comment by lstreepy** [comment]
I don't see any way to get hold of values that are entered interactively using that.

**Comment by orctom** [comment]
Could you provide more details on your needs.

And yes please make a PR.

**Comment by lstreepy** [comment]
Sorry to be an idiot, but if I can't push my branch to your repo, how do I submit a PR?  Do I need to make my own fork and then issue it from there?  I'll attach a patch until I figure out how to do the PR properly.

**Comment by lstreepy** [comment]
[issue26.patch.txt](https://github.com/orctom/gradle-archetype-plugin/files/1925335/issue26.patch.txt)

**Comment by orctom** [comment]
Please find it in `1.4.7`
