### ISSUE TITLE
Publish versions 2.x.x and later to public repositories 

### ISSUE THREAD

**Issue by davoros** [orctom/gradle-archetype-plugin#44]
Dear orctom Team,

thank you for this awesome plugin!

Is it possible to publish version 2.0.0 and later to gradle / maven public repositories. The last published version is 1.4.8 from 11. 2019:

- https://plugins.gradle.org/plugin/com.orctom.archetype
- https://mvnrepository.com/artifact/gradle.plugin.com.orctom.gradle/gradle-archetype-plugin

Cheers,
Davor

**Comment by orctom** [comment]
there

**Comment by davoros** [comment]
Thanks!
