### ISSUE TITLE
additional variables

### ISSUE THREAD

**Issue by mikexliu** [orctom/gradle-archetype-plugin#6]
I'm wondering if it would be possible to add these standard variables in (any suggestions welcome):

Starting strings:

| name             | description                                    | type      | sample                |
| -----------------| -----------------------------------------------| ----------| ----------------------|
| group            | project.group                                  | string    | com.xxx.yyy           |
| name             | project.name                                   | string    | dummy-app             |
| version          | project.version                                | string    | 1.0-SNAPSHOT          |

Generates the following:

| name             | description                                    | type      | sample                |
| -----------------| -----------------------------------------------| ----------| ----------------------|
| packageName      | name replacing '-' with '.'                    | string    | dummy.app             |
| nameFolderPath   | name replacing '.' with '/'                    | directory | dummy/app             |
| groupFolderPath  | group replacing non-characters with '/'        | directory | com/xxx/yyy           |
| fullPackageName  | group + name replacing non-characters with '.' | string | com.xxx.yyy.dummy.app |
| fullPackagePath  | replaced '.' with '/' in packageName           | directory | com/xxx/yyy/dummy/app |

This is for when I create a new project, I want to use a name like `simple-service`. Normally I'd be able to just use `fullPackagePath` but sometimes, I want to break it up like `${groupFolderPath}/outside/module/${nameFolderPath}` instead. The `package ...` line in the code has to be created with: `${group}.outside.module.${packageName}` which is impossible to generate as is currently.

I can try adding these myself but I don't want to change any variable names from what is already there so I figure I should let you handle it. :P

Fyi, this is a great project. Thanks for it!!

**Comment by mikexliu** [comment]
I can try adding these myself but I don't want to change any variable names from what is already there so I figure I should let you handle it. :P

**Comment by orctom** [comment]
If you understood you correctly, you'll just need `nameFolderPath`, I'll probably name it as `namePath`.
As it already provides `packageName`, `groupPath` (as to your `groupFolderPath`), `packageName` (as to your `fullPackageName`), `packagePath` (as to your `fullPackagePath`)

https://github.com/orctom/gradle-archetype-plugin#variables

Correct me if I'm wrong.

**Comment by mikexliu** [comment]
Two:

`packagePath` (dummy.app) and `nameFolderPath` (dummy/app).
Maybe your docs are wrong but you have both `name` and `projectName` mapped to `dummy-app`.

**Comment by orctom** [comment]
Yeah, I missed that one. While for `projectName` I made it the same as `name`, like alias, seems trivial, but better to keep it as it is.

Checkout 1.3.1
