### ISSUE TITLE
Plugin failure with Gradle 3.x

### ISSUE THREAD

**Issue by dchesterman** [orctom/gradle-archetype-plugin#8]
```
* What went wrong:
A problem occurred evaluating root project 'gradle-archetypes'.
> Failed to apply plugin [id 'com.orctom.archetype']
   > Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed.
```
I think this error message is related to below description at Gradle 3.0 Release note (Changes to previously deprecated APIs);

> Declaring custom check, clean, build or assemble tasks is not allowed anymore when using the lifecycle plugin.

https://docs.gradle.org/3.0/release-notes

**Comment by dchesterman** [comment]
Any chance we can change the name of the task?

**Comment by orctom** [comment]
Suggestions for the task name?

**Comment by orctom** [comment]
What's the exact version you are using, btw?

**Comment by dchesterman** [comment]
I'm using 3.3.

"cleanGeneratedProjects" or something?

I wonder if instead you could update the existing `clean` task in the plugin apply() method to clean the destination dir as well, rather than create a new task.

**Comment by orctom** [comment]
It's weird, cause 3.3 works fine for me.
`cleanGeneratedProjects` a little bit too long, you'll have to type at least `cleanG`, 

The first run, when you don't have the `generated` directory, and you run `gradle generate -i`, will this error happen? If not, I'm to add another task doing the clean job, and keep the `clean` task for those who doesn't have issue with the `clean` lifecycle.

One of the users wants it be optional to clean, like don't delete generated files of last run, then generate it again... so, made it a separate task.

**Comment by dchesterman** [comment]
Ah its with another plugin applied. It may be any of the delivered plugins... fails with `java`, `groovy`, `distribution`, a few others.  I can't find one of the delivered ones it is compatible with.  There may be but haven't test all of them.

Maybe `archClean` or something?

**Comment by orctom** [comment]
`archClean` is good, but once we have it renamed, current users will be affected, if they move on the later version.

So I want to see if we really have to have it renamed.
What plugins you have in your cookie cutter build.gradle? Are they mandatory?

**Comment by orctom** [comment]
Anyway, I have it renamed, but changed to `cleanArchetype`, as I see the clean task for `idea` plugin is called `cleanIdea`.
Well, you can use `cleanArch` or even `cleanA`, since gradle supports the task name guessing.

Checkout `1.4`.

**Comment by dchesterman** [comment]
Thanks for the changes and release!
